[toolchain]
anchor_version = "0.30.1"
[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_transfer = "HijJ2gR2jwjGwyLCvSu5sJbhEN2pjD33rbpLs2mZjPJM"
[programs.devnet]
sol_transfer = "CjU8CvewB2FZrM4DL43BhoMXHS2bfo68hXwcHGEzPmiU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
